import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
import axios from 'axios';
import Swal from 'sweetalert2'

export default function Home() {
  const token = 'your-token';
  const [courier, setCourier] = useState([]);
  const [awb, setAwb] = useState([]);
  const [historyresi, setHistory] = useState([]);
  const [sumary, setSumary] = useState([]);

  const getDataResi = async (e) => {
    e.preventDefault();
    let timerInterval
    Swal.fire({
      title: 'Tunggu Sebentar!',
      html: 'Sedang Memuat Data.',
      timer: 2000,
      timerProgressBar: true,
      didOpen: () => {
        Swal.showLoading()
        const b = Swal.getHtmlContainer().querySelector('b')
        timerInterval = setInterval(() => {
        }, 100)
      },
      willClose: () => {
        clearInterval(timerInterval)
      }
    }).then((result) => {
      /* Read more about handling dismissals below */
      if (result.dismiss === Swal.DismissReason.timer) {
        console.log('I was closed by the timer')
      }
    })
    try {
      const result = await axios.get(`https://api.binderbyte.com/v1/track?api_key=${token}&courier=${courier}&awb=${awb}`);
      setHistory(result.data.data.history);
      setSumary(result.data.data.summary);
      console.log(historyresi)
    }
    catch (error) {
      Swal.fire({
        title: 'Error!',
        text: 'Data Tidak Di Temukan',
        icon: 'error',
        confirmButtonText: 'Oke'
      })
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Cek Resi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Cek Resi!</a>
        </h1>

        <div className="container p-5">
          <div className="card">
            <div className="card-header">
              Masukkan Resi Anda
            </div>
            <div className="card-body">
              <form onSubmit={getDataResi}>
                <div className="mb-3">
                  <label for="exampleInputEmail1" className="form-label">Ekspedisi</label>
                  <select className="form-control" onChange={(e) => setCourier(e.target.value)} required>
                    <option value="">Pilih Ekspedisi</option>
                    <option value="jne" >JNE</option>
                    <option value="pos" >POS INDONESIA</option>
                    <option value="jnt" >J&T</option>
                    <option value="sicepat"> SICEPAT</option>
                    <option value="tiki">TIKI</option>
                    <option value="anteraja">ANTERAJA</option>
                    <option value="wahana">WAHANA</option>
                    <option value="ninja">NINJA</option>
                    <option value="lion">LION</option>
                    <option value="pcp">PCP EXPRESS</option>
                    <option value="jet">JET EXPRESS</option>
                    <option value="rex">REX EXPRESS</option>
                    <option value="first">First Logistics</option>
                    <option value="ide">ID Express</option>
                    <option value="spx">Shopee Express</option>
                  </select>
                  <div id="emailHelp" className="form-text">Silahkan pilih ekspedisi.</div>
                </div>
                <div className="mb-3">
                  <label for="exampleInputPassword1" className="form-label">Nomor Resi</label>
                  <input type="text" className="form-control" value={awb} onChange={(e) => setAwb(e.target.value)} required />
                  <div id="emailHelp" className="form-text">Masukkan Nomor resi Anda.</div>
                </div>
                <button type="submit" className="btn btn-primary">Submit</button>&nbsp;
                <button className="btn btn-success" onClick={() => window.location.reload(false)}>Refresh</button>
              </form>
            </div>
          </div><br />
          <div class="card bg-primary">
            <div class="card-header text-white">
              Hasil tracked
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">No Resi&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: &nbsp;{sumary.awb}</li>
              <li class="list-group-item">Exspedisi&nbsp;&nbsp;&nbsp;: &nbsp;{sumary.courier}</li>
              <li class="list-group-item">Status&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: &nbsp;<span class="badge bg-success">{sumary.status}</span></li>
              <li class="list-group-item">
                History
                <ul>
                  {historyresi.map(resi => {
                    return (
                      <li key={resi.id}>
                        <span class="badge bg-primary">{resi.date}</span><br />
                        <ul class="list-group">
                          <li class="list-group-item">{resi.desc}</li>
                          <li class="list-group-item fw-bold">{resi.location}</li>
                        </ul><br />
                      </li>
                    )
                  })}
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' Romadhani '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
